services:
  nginx:
    image: nginx:1.20.1
    container_name: battleship-reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    depends_on:
      - frontend
      - backend
      - mongo

  mongo:
    image: mongo
    environment:
      - DB_DATABASE_NAME
      - DB_USER_USERNAME
      - DB_USER_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./db/data/dev:/data/db

  frontend:
    image: battleship-client-dev
    build:
      dockerfile: packages/client/dev.Dockerfile
    container_name: battleship-client-dev
    secrets:
      - source: client-env-key
        target: /usr/src/app/packages/client/.env.keys
    expose:
      - 8080
    volumes:
      - ./:/usr/src/app
    depends_on:
      - backend

  backend:
    image: battleship-server-dev
    build:
      dockerfile: packages/server/dev.Dockerfile
    container_name: battleship-server-dev
    secrets:
      - source: server-env-key
        target: /usr/src/app/packages/server/.env.keys
    expose:
      - $PORT
      - $WS_PORT
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo
  
secrets:
  client-env-key:
    file: packages/client/.env.keys
  server-env-key:
    file: packages/server/.env.keys
