services:
  nginx:
    image: nginx:1.20.1
    container_name: battleship-reverse-proxy-prod
    secrets:
      - source: ssl-cert-key
        target: /etc/nginx/www.playbattleship.com.key
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www.playbattleship.com.crt:/etc/nginx/www.playbattleship.com.crt
    ports:
      - 443:443
    depends_on:
      - frontend
      - backend
      - mongo

  mongo:
    image: mongo
    container_name: battleship-mongo-prod
    environment:
      - DB_DATABASE_NAME
      - DB_USER_USERNAME
      - DB_USER_PASSWORD
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./db/data/prod:/data/db

  frontend:
    image: battleship-client-prod
    build:
      no_cache: true
      dockerfile: packages/client/Dockerfile
      secrets:
      - client-env-key
    container_name: battleship-client-prod
    volumes:
      - ./packages/client/assets/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - 80
    depends_on:
      - backend

  backend:
    image: battleship-server-prod
    build:
      no_cache: true
      dockerfile: packages/server/Dockerfile
      secrets:
        - server-env-key
    container_name: battleship-server-prod
    secrets:
      - source: server-env-key
        target: /usr/src/app/packages/server/.env.keys
    expose:
      - $PORT
      - $WS_PORT
    depends_on:
      - mongo
  
secrets:
  client-env-key:
    file: packages/client/.env.keys
  server-env-key:
    file: packages/server/.env.keys
  ssl-cert-key:
    file: ./www.playbattleship.com.key
