import { ShipOrientation, ShipClassName } from '../../__generated__/graphql';
import { SliceState } from './types';

export const placedState: SliceState = {
  placedIDs: [
    'CARRIER-1',
    'BATTLESHIP-1',
    'CRUISER-1',
    'DESTROYER-1',
    'DESTROYER-2',
    'SUBMARINE-2',
    'SUBMARINE-1',
  ],
  nonPlacedIDs: [],
  shipStates: [
    {
      shipID: 'CARRIER-1',
      shipClass: {
        __typename: 'ShipClass',
        size: 5,
        type: 'CARRIER',
      },
      orientation: 'HORIZONTAL',
      position: {
        x: 0,
        y: 1,
      },
    },
    {
      shipID: 'BATTLESHIP-1',
      shipClass: {
        __typename: 'ShipClass',
        size: 4,
        type: 'BATTLESHIP',
      },
      orientation: 'HORIZONTAL',
      position: {
        x: 6,
        y: 0,
      },
    },
    {
      shipID: 'CRUISER-1',
      shipClass: {
        __typename: 'ShipClass',
        size: 3,
        type: 'CRUISER',
      },
      orientation: 'HORIZONTAL',
      position: {
        x: 0,
        y: 3,
      },
    },
    {
      shipID: 'DESTROYER-1',
      shipClass: {
        __typename: 'ShipClass',
        size: 2,
        type: 'DESTROYER',
      },
      orientation: 'HORIZONTAL',
      position: {
        x: 7,
        y: 2,
      },
    },
    {
      shipID: 'DESTROYER-2',
      shipClass: {
        __typename: 'ShipClass',
        size: 2,
        type: 'DESTROYER',
      },
      orientation: 'HORIZONTAL',
      position: {
        x: 4,
        y: 5,
      },
    },
    {
      shipID: 'SUBMARINE-1',
      shipClass: {
        __typename: 'ShipClass',
        size: 1,
        type: 'SUBMARINE',
      },
      orientation: 'HORIZONTAL',
      position: {
        x: 1,
        y: 7,
      },
    },
    {
      shipID: 'SUBMARINE-2',
      shipClass: {
        __typename: 'ShipClass',
        size: 1,
        type: 'SUBMARINE',
      },
      orientation: 'HORIZONTAL',
      position: {
        x: 8,
        y: 7,
      },
    },
  ],
  grid: {
    columns: 10,
    rows: 10,
    cellStates: [
      [
        null,
        null,
        null,
        null,
        null,
        null,
        'BATTLESHIP-1',
        'BATTLESHIP-1',
        'BATTLESHIP-1',
        'BATTLESHIP-1',
      ],
      [
        'CARRIER-1',
        'CARRIER-1',
        'CARRIER-1',
        'CARRIER-1',
        'CARRIER-1',
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        'DESTROYER-1',
        'DESTROYER-1',
        null,
      ],
      [
        'CRUISER-1',
        'CRUISER-1',
        'CRUISER-1',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        'DESTROYER-2',
        'DESTROYER-2',
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        'SUBMARINE-1',
        null,
        null,
        null,
        null,
        null,
        null,
        'SUBMARINE-2',
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
    ],
  },
};

export const emptyState: SliceState = {
  placedIDs: [],
  nonPlacedIDs: [
    'CARRIER-1',
    'BATTLESHIP-1',
    'CRUISER-1',
    'DESTROYER-1',
    'DESTROYER-2',
    'SUBMARINE-1',
    'SUBMARINE-2',
  ],
  shipStates: [
    {
      orientation: ShipOrientation.Horizontal, shipClass: { size: 5, type: ShipClassName.Carrier }, position: null, shipID: 'CARRIER-1',
    },
    {
      orientation: ShipOrientation.Horizontal, shipClass: { size: 4, type: ShipClassName.Battleship }, position: null, shipID: 'BATTLESHIP-1',
    },
    {
      orientation: ShipOrientation.Horizontal, shipClass: { size: 3, type: ShipClassName.Cruiser }, position: null, shipID: 'CRUISER-1',
    },
    {
      orientation: ShipOrientation.Horizontal, shipClass: { size: 2, type: ShipClassName.Destroyer }, position: null, shipID: 'DESTROYER-1',
    },
    {
      orientation: ShipOrientation.Horizontal, shipClass: { size: 2, type: ShipClassName.Destroyer }, position: null, shipID: 'DESTROYER-2',
    },
    {
      orientation: ShipOrientation.Horizontal, shipClass: { size: 1, type: ShipClassName.Submarine }, position: null, shipID: 'SUBMARINE-1',
    },
    {
      orientation: ShipOrientation.Horizontal, shipClass: { size: 1, type: ShipClassName.Submarine }, position: null, shipID: 'SUBMARINE-2',
    },
  ],
  grid: {
    columns: 10,
    rows: 10,
    cellStates: [
      [null, null, null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null, null, null],
      [null, null, null, null, null, null, null, null, null, null],
    ],
  },
};
